In [1]:
import pandas as pd

file_path = '../data/Imputation_Test.xlsx'
sheet_index = 0
data = pd.read_excel(file_path, sheet_name=sheet_index)

In [2]:
data.head(10)

,데이터분류,Unnamed: 1,Unnamed: 2,Unnamed: 3,입고시 인수 검사,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,기타
0,실험일자,실험목적 및 실험명,실험차수,유일값,입고일,번호,분류1,분류2,XRF 산화물(%),NaN,...,Flow\n(mm),강도 Compressive strength(Mpa),NaN,NaN,NaN,NaN,NaN,NaN,NaN,추가정보
1,Exp_Date,Exp_Name,Batch,Index,RMth,No,Class1,Class2,CaO,Al2O3,...,Flow,H3,H4,D1,D3,D28,D91,D180,D365,비고
2,210323,슬래그 기초특성 평가,01,210323-01,2020.09,1,세아,급결재,50.71,27.52,...,215,0.7,NaN,5.9,14.7,29.1,NaN,NaN,NaN,NaN
3,210323,슬래그 기초특성 평가,02,210323-02,2020.09,2,세아,시멘트,50.71,27.52,...,230,20.5,NaN,37.9,34.1,48.1,NaN,NaN,NaN,NaN
4,210323,슬래그 기초특성 평가,03,210323-03,2020.09,3,세아,시멘트,50.71,27.52,...,185,5.3,NaN,27.5,28.7,40.2,NaN,NaN,NaN,NaN
5,210323,슬래그 기초특성 평가,04,210323-04,2020.09,4,세아,시멘트,50.71,27.52,...,210,2.9,NaN,12,12.2,17.5,NaN,NaN,NaN,NaN
6,210427,슬래그 기초특성 평가,01,210427-01,2021.02,1,세아,급결재,55.21,24.35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,210427,슬래그 기초특성 평가,02,210427-02,2021.02,2,세아,시멘트,55.21,24.35,...,182.5,0.5,NaN,0.7,0.7,NaN,NaN,NaN,NaN,NaN
8,210427,슬래그 기초특성 평가,03,210427-03,2021.02,3,세아,시멘트,55.21,24.35,...,165,NaN,NaN,0.8,1,NaN,NaN,NaN,NaN,NaN
9,210427,슬래그 기초특성 평가,04,210427-04,2021.04,1,세아,급결재,49.07,29.81,...,230,1.1,NaN,3.3,14,NaN,NaN,NaN,NaN,NaN

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 70 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   데이터분류              607 non-null    object
 1   Unnamed: 1         607 non-null    object
 2   Unnamed: 2         607 non-null    object
 3   Unnamed: 3         607 non-null    object
 4   입고시 인수 검사          607 non-null    object
 5   Unnamed: 5         607 non-null    object
 6   Unnamed: 6         607 non-null    object
 7   Unnamed: 7         607 non-null    object
 8   Unnamed: 8         607 non-null    object
 9   Unnamed: 9         606 non-null    object
 10  Unnamed: 10        606 non-null    object
 11  Unnamed: 11        606 non-null    object
 12  Unnamed: 12        606 non-null    object
 13  Unnamed: 13        606 non-null    object
 14  Unnamed: 14        606 non-null    object
 15  Unnamed: 15        586 non-null    object
 16  분쇄 후 중간 검사         571 non-null    object
 17  Unnamed: 17        583 non-null    object
 18  Unnamed: 18        569 non-null    object
 19  첨가제 및 공정 특성치(CTP)  501 non-null    object
 20  Unnamed: 20        500 non-null    object
 21  Unnamed: 21        500 non-null    object
 22  Unnamed: 22        499 non-null    object
 23  Unnamed: 23        201 non-null    object
 24  Unnamed: 24        200 non-null    object
 25  Unnamed: 25        200 non-null    object
 26  Unnamed: 26        200 non-null    object
 27  Unnamed: 27        200 non-null    object
 28  Unnamed: 28        200 non-null    object
 29  Unnamed: 29        438 non-null    object
 30  Unnamed: 30        438 non-null    object
 31  Unnamed: 31        438 non-null    object
 32  Unnamed: 32        438 non-null    object
 33  Unnamed: 33        438 non-null    object
 34  Unnamed: 34        185 non-null    object
 35  Unnamed: 35        184 non-null    object
 36  Unnamed: 36        184 non-null    object
 37  Unnamed: 37        184 non-null    object
 38  Unnamed: 38        184 non-null    object
 39  Unnamed: 39        184 non-null    object
 40  Unnamed: 40        184 non-null    object
 41  Unnamed: 41        184 non-null    object
 42  Unnamed: 42        184 non-null    object
 43  Unnamed: 43        184 non-null    object
 44  Unnamed: 44        184 non-null    object
 45  Unnamed: 45        184 non-null    object
 46  Unnamed: 46        36 non-null     object
 47  Unnamed: 47        35 non-null     object
 48  Unnamed: 48        137 non-null    object
 49  Unnamed: 49        136 non-null    object
 50  Unnamed: 50        136 non-null    object
 51  Unnamed: 51        559 non-null    object
 52  Unnamed: 52        558 non-null    object
 53  Unnamed: 53        558 non-null    object
 54  Unnamed: 54        558 non-null    object
 55  Unnamed: 55        429 non-null    object
 56  품질특성치 (CTQ)        367 non-null    object
 57  Unnamed: 57        366 non-null    object
 58  Unnamed: 58        366 non-null    object
 59  Unnamed: 59        77 non-null     object
 60  Unnamed: 60        208 non-null    object
 61  Unnamed: 61        258 non-null    object
 62  Unnamed: 62        43 non-null     object
 63  Unnamed: 63        225 non-null    object
 64  Unnamed: 64        190 non-null    object
 65  Unnamed: 65        192 non-null    object
 66  Unnamed: 66        27 non-null     object
 67  Unnamed: 67        27 non-null     object
 68  Unnamed: 68        27 non-null     object
 69  기타                 2 non-null      object
dtypes: object(70)
memory usage: 332.1+ KB

---

In [4]:
df = data.copy()
df = df.iloc[:, 3:]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 67 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 3         607 non-null    object
 1   입고시 인수 검사          607 non-null    object
 2   Unnamed: 5         607 non-null    object
 3   Unnamed: 6         607 non-null    object
 4   Unnamed: 7         607 non-null    object
 5   Unnamed: 8         607 non-null    object
 6   Unnamed: 9         606 non-null    object
 7   Unnamed: 10        606 non-null    object
 8   Unnamed: 11        606 non-null    object
 9   Unnamed: 12        606 non-null    object
 10  Unnamed: 13        606 non-null    object
 11  Unnamed: 14        606 non-null    object
 12  Unnamed: 15        586 non-null    object
 13  분쇄 후 중간 검사         571 non-null    object
 14  Unnamed: 17        583 non-null    object
 15  Unnamed: 18        569 non-null    object
 16  첨가제 및 공정 특성치(CTP)  501 non-null    object
 17  Unnamed: 20        500 non-null    object
 18  Unnamed: 21        500 non-null    object
 19  Unnamed: 22        499 non-null    object
 20  Unnamed: 23        201 non-null    object
 21  Unnamed: 24        200 non-null    object
 22  Unnamed: 25        200 non-null    object
 23  Unnamed: 26        200 non-null    object
 24  Unnamed: 27        200 non-null    object
 25  Unnamed: 28        200 non-null    object
 26  Unnamed: 29        438 non-null    object
 27  Unnamed: 30        438 non-null    object
 28  Unnamed: 31        438 non-null    object
 29  Unnamed: 32        438 non-null    object
 30  Unnamed: 33        438 non-null    object
 31  Unnamed: 34        185 non-null    object
 32  Unnamed: 35        184 non-null    object
 33  Unnamed: 36        184 non-null    object
 34  Unnamed: 37        184 non-null    object
 35  Unnamed: 38        184 non-null    object
 36  Unnamed: 39        184 non-null    object
 37  Unnamed: 40        184 non-null    object
 38  Unnamed: 41        184 non-null    object
 39  Unnamed: 42        184 non-null    object
 40  Unnamed: 43        184 non-null    object
 41  Unnamed: 44        184 non-null    object
 42  Unnamed: 45        184 non-null    object
 43  Unnamed: 46        36 non-null     object
 44  Unnamed: 47        35 non-null     object
 45  Unnamed: 48        137 non-null    object
 46  Unnamed: 49        136 non-null    object
 47  Unnamed: 50        136 non-null    object
 48  Unnamed: 51        559 non-null    object
 49  Unnamed: 52        558 non-null    object
 50  Unnamed: 53        558 non-null    object
 51  Unnamed: 54        558 non-null    object
 52  Unnamed: 55        429 non-null    object
 53  품질특성치 (CTQ)        367 non-null    object
 54  Unnamed: 57        366 non-null    object
 55  Unnamed: 58        366 non-null    object
 56  Unnamed: 59        77 non-null     object
 57  Unnamed: 60        208 non-null    object
 58  Unnamed: 61        258 non-null    object
 59  Unnamed: 62        43 non-null     object
 60  Unnamed: 63        225 non-null    object
 61  Unnamed: 64        190 non-null    object
 62  Unnamed: 65        192 non-null    object
 63  Unnamed: 66        27 non-null     object
 64  Unnamed: 67        27 non-null     object
 65  Unnamed: 68        27 non-null     object
 66  기타                 2 non-null      object
dtypes: object(67)
memory usage: 317.9+ KB

In [6]:
stocking = df.iloc[:, :13]
stocking.columns = stocking.iloc[1]
stocking = stocking.drop([0, 1]).reset_index(drop=True)
stocking

1,Index,RMth,No,Class1,Class2,CaO,Al2O3,SiO2,Fe2O3,SO3,MgO,etc,FM
0,210323-01,2020.09,1,세아,급결재,50.71,27.52,8.15,2.23,3.95,5.8,1.64,2.56
1,210323-02,2020.09,2,세아,시멘트,50.71,27.52,8.15,2.23,3.95,5.8,1.64,2.56
2,210323-03,2020.09,3,세아,시멘트,50.71,27.52,8.15,2.23,3.95,5.8,1.64,2.56
3,210323-04,2020.09,4,세아,시멘트,50.71,27.52,8.15,2.23,3.95,5.8,1.64,2.56
4,210427-01,2021.02,1,세아,급결재,55.21,24.35,6.04,1.08,5.5,6.74,1.08,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,250224-02,2024.12,2,현대,시멘트,46.7,31.2,11.2,3.18,0.573,4.04,3.107,4.5
601,250304-01,2024.11,1,세아,시멘트,49.1,27.28,11.62,1.18,4.29,5.42,1.11,3.36
602,250304-02,2024.11,1,세아,시멘트,49.1,27.28,11.62,1.18,4.29,5.42,1.11,3.36
603,250304-03,2024.12,1,현대,시멘트,46.7,31.2,11.2,3.18,0.573,4.04,3.107,4.5
604,250305-04,2024.12,1,현대,시멘트,46.7,31.2,11.2,3.18,0.573,4.04,3.107,4.5

In [7]:
middle = df.iloc[:, 13:16]
middle.columns = middle.iloc[1]
middle = middle.drop([0, 1]).reset_index(drop=True)
middle

1    MeanV Density  Blain
0      NaN    2.87   6012
1      NaN    2.87   6012
2      NaN    2.87   6012
3      NaN    2.87   6012
4      NaN    2.87   6051
..     ...     ...    ...
600  9.274    3.02   7127
601  12.26    2.97  5.858
602  12.26    2.97  5.858
603  9.274    3.02   7127
604  9.274    3.02   7127

[605 rows x 3 columns]

In [8]:
ctp = df.iloc[:, 16:53]
ctp.columns = ctp.iloc[1]
ctp = ctp.drop([0, 1]).reset_index(drop=True)
ctp

1,HG,AG,DG,Gyp_per,CA_Before,GS_Before,JA_Before,CS_Before,BA_Before,Delay_Bf_per,...,LC_brfore,Hard_per,SPP_before,SPP_after,FlowRate_per,WC35,WC40,WC50,W60,WC_per
0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,1,0,0.5
1,1,0,0,25,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,1,0,0.5
2,0,0,1,40,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,1,0,0.5
3,0,1,0,40,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,1,0,0.5
4,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,1,0,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,1,0,0,25,1,0,0,0,0,0.03,...,1,0.0005,1,0,0.001,0,0,1,0,0.5
601,1,0,0,25,1,0,0,0,0,0.01,...,1,0.0005,1,0,0.001,0,0,1,0,0.5
602,1,0,0,25,1,0,0,0,0,0.01,...,1,0.0005,1,0,0.001,0,0,1,0,0.5
603,1,0,0,25,1,0,0,0,0,0.02,...,1,0.0005,1,0,0.001,0,0,1,0,0.5
604,1,0,0,25,1,0,0,0,0,0.02,...,1,0.0005,1,0,0.001,0,0,1,0,0.5

In [9]:
ctq = df.iloc[:, 53:66]
ctq.columns = ctq.iloc[1]
ctq = ctq.drop([0, 1]).reset_index(drop=True)
ctq

1,Initial,Final,Interval,H2S,Flow,H3,H4,D1,D3,D28,D91,D180,D365
0,90,130,40,NaN,215,0.7,NaN,5.9,14.7,29.1,NaN,NaN,NaN
1,16,18,2,NaN,230,20.5,NaN,37.9,34.1,48.1,NaN,NaN,NaN
2,128,138,10,NaN,185,5.3,NaN,27.5,28.7,40.2,NaN,NaN,NaN
3,4,8,4,NaN,210,2.9,NaN,12,12.2,17.5,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,NaN,NaN,NaN,NaN,212.5,27.8,30.5,40.1,NaN,48.7,NaN,NaN,NaN
601,NaN,NaN,NaN,NaN,202.5,31.6,34.5,40.1,NaN,44.6,NaN,NaN,NaN
602,NaN,NaN,NaN,NaN,252.5,35.7,36.8,42.5,NaN,54.3,NaN,NaN,NaN
603,NaN,NaN,NaN,NaN,227.5,17.4,16.6,22,NaN,35.6,NaN,NaN,NaN
604,NaN,NaN,NaN,NaN,205,26.3,27.3,46.3,NaN,54.6,NaN,NaN,NaN

---

In [10]:
ctp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 37 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HG            499 non-null    object
 1   AG            499 non-null    object
 2   DG            499 non-null    object
 3   Gyp_per       498 non-null    object
 4   CA_Before     199 non-null    object
 5   GS_Before     199 non-null    object
 6   JA_Before     199 non-null    object
 7   CS_Before     199 non-null    object
 8   BA_Before     199 non-null    object
 9   Delay_Bf_per  199 non-null    object
 10  CA_after      437 non-null    object
 11  BA_after      437 non-null    object
 12  CS_after      437 non-null    object
 13  SC_after      437 non-null    object
 14  Delay_Af_per  437 non-null    object
 15  ZS_Before     183 non-null    object
 16  ZS_Milling    183 non-null    object
 17  ZS_After      183 non-null    object
 18  H2O2_After    183 non-null    object
 19  IS_Before     183 non-null    object
 20  FeCl2_After   183 non-null    object
 21  FeS_After     183 non-null    object
 22  I_Before      183 non-null    object
 23  ZX_Before     183 non-null    object
 24  PP_Before     183 non-null    object
 25  MS_Before     183 non-null    object
 26  H2S_per       183 non-null    object
 27  LC_brfore     34 non-null     object
 28  Hard_per      34 non-null     object
 29  SPP_before    135 non-null    object
 30  SPP_after     135 non-null    object
 31  FlowRate_per  135 non-null    object
 32  WC35          557 non-null    object
 33  WC40          557 non-null    object
 34  WC50          557 non-null    object
 35  W60           557 non-null    object
 36  WC_per        428 non-null    object
dtypes: object(37)
memory usage: 175.0+ KB

In [11]:
temp = ctp.iloc[:, 4:]
temp = temp.apply(lambda col: pd.to_numeric(col, errors='coerce'))
temp = temp.fillna(0)
temp

1,CA_Before,GS_Before,JA_Before,CS_Before,BA_Before,Delay_Bf_per,CA_after,BA_after,CS_after,SC_after,...,LC_brfore,Hard_per,SPP_before,SPP_after,FlowRate_per,WC35,WC40,WC50,W60,WC_per
0,0.0,0.0,0.0,0.0,0.0,0.00,1.0,0.0,0.0,0.0,...,0.0,0.0000,0.0,0.0,0.000,0.0,0.0,1.0,0.0,0.5
1,0.0,0.0,0.0,0.0,0.0,0.00,1.0,0.0,0.0,0.0,...,0.0,0.0000,0.0,0.0,0.000,0.0,0.0,1.0,0.0,0.5
2,0.0,0.0,0.0,0.0,0.0,0.00,1.0,0.0,0.0,0.0,...,0.0,0.0000,0.0,0.0,0.000,0.0,0.0,1.0,0.0,0.5
3,0.0,0.0,0.0,0.0,0.0,0.00,1.0,0.0,0.0,0.0,...,0.0,0.0000,0.0,0.0,0.000,0.0,0.0,1.0,0.0,0.5
4,0.0,0.0,0.0,0.0,0.0,0.00,1.0,0.0,0.0,0.0,...,0.0,0.0000,0.0,0.0,0.000,0.0,0.0,1.0,0.0,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,1.0,0.0,0.0,0.0,0.0,0.03,0.0,0.0,0.0,0.0,...,1.0,0.0005,1.0,0.0,0.001,0.0,0.0,1.0,0.0,0.5
601,1.0,0.0,0.0,0.0,0.0,0.01,0.0,0.0,0.0,0.0,...,1.0,0.0005,1.0,0.0,0.001,0.0,0.0,1.0,0.0,0.5
602,1.0,0.0,0.0,0.0,0.0,0.01,0.0,0.0,0.0,0.0,...,1.0,0.0005,1.0,0.0,0.001,0.0,0.0,1.0,0.0,0.5
603,1.0,0.0,0.0,0.0,0.0,0.02,0.0,0.0,0.0,0.0,...,1.0,0.0005,1.0,0.0,0.001,0.0,0.0,1.0,0.0,0.5
604,1.0,0.0,0.0,0.0,0.0,0.02,0.0,0.0,0.0,0.0,...,1.0,0.0005,1.0,0.0,0.001,0.0,0.0,1.0,0.0,0.5

In [12]:
ctp = pd.concat([ctp.iloc[:, :4], temp], axis=1)
ctp

1,HG,AG,DG,Gyp_per,CA_Before,GS_Before,JA_Before,CS_Before,BA_Before,Delay_Bf_per,...,LC_brfore,Hard_per,SPP_before,SPP_after,FlowRate_per,WC35,WC40,WC50,W60,WC_per
0,0,0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0000,0.0,0.0,0.000,0.0,0.0,1.0,0.0,0.5
1,1,0,0,25,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0000,0.0,0.0,0.000,0.0,0.0,1.0,0.0,0.5
2,0,0,1,40,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0000,0.0,0.0,0.000,0.0,0.0,1.0,0.0,0.5
3,0,1,0,40,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0000,0.0,0.0,0.000,0.0,0.0,1.0,0.0,0.5
4,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0000,0.0,0.0,0.000,0.0,0.0,1.0,0.0,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,1,0,0,25,1.0,0.0,0.0,0.0,0.0,0.03,...,1.0,0.0005,1.0,0.0,0.001,0.0,0.0,1.0,0.0,0.5
601,1,0,0,25,1.0,0.0,0.0,0.0,0.0,0.01,...,1.0,0.0005,1.0,0.0,0.001,0.0,0.0,1.0,0.0,0.5
602,1,0,0,25,1.0,0.0,0.0,0.0,0.0,0.01,...,1.0,0.0005,1.0,0.0,0.001,0.0,0.0,1.0,0.0,0.5
603,1,0,0,25,1.0,0.0,0.0,0.0,0.0,0.02,...,1.0,0.0005,1.0,0.0,0.001,0.0,0.0,1.0,0.0,0.5
604,1,0,0,25,1.0,0.0,0.0,0.0,0.0,0.02,...,1.0,0.0005,1.0,0.0,0.001,0.0,0.0,1.0,0.0,0.5

In [13]:
ctp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 37 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HG            499 non-null    object
 1   AG            499 non-null    object
 2   DG            499 non-null    object
 3   Gyp_per       498 non-null    object
 4   CA_Before     605 non-null    float64
 5   GS_Before     605 non-null    float64
 6   JA_Before     605 non-null    float64
 7   CS_Before     605 non-null    float64
 8   BA_Before     605 non-null    float64
 9   Delay_Bf_per  605 non-null    float64
 10  CA_after      605 non-null    float64
 11  BA_after      605 non-null    float64
 12  CS_after      605 non-null    float64
 13  SC_after      605 non-null    float64
 14  Delay_Af_per  605 non-null    float64
 15  ZS_Before     605 non-null    float64
 16  ZS_Milling    605 non-null    float64
 17  ZS_After      605 non-null    float64
 18  H2O2_After    605 non-null    float64
 19  IS_Before     605 non-null    float64
 20  FeCl2_After   605 non-null    float64
 21  FeS_After     605 non-null    float64
 22  I_Before      605 non-null    float64
 23  ZX_Before     605 non-null    float64
 24  PP_Before     605 non-null    float64
 25  MS_Before     605 non-null    float64
 26  H2S_per       605 non-null    float64
 27  LC_brfore     605 non-null    float64
 28  Hard_per      605 non-null    float64
 29  SPP_before    605 non-null    float64
 30  SPP_after     605 non-null    float64
 31  FlowRate_per  605 non-null    float64
 32  WC35          605 non-null    float64
 33  WC40          605 non-null    float64
 34  WC50          605 non-null    float64
 35  W60           605 non-null    float64
 36  WC_per        605 non-null    float64
dtypes: float64(33), object(4)
memory usage: 175.0+ KB

---

In [14]:
stocking.to_csv("stocking.csv", index=True)
middle.to_csv("middle.csv", index=True)
ctp.to_csv("ctp.csv", index=True)
ctq.to_csv("ctq.csv", index=True)